language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - ruby-head
bundler_args: --without development
script: bundle exec rspec
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.1.0 
notifications:
  recipients:
    - iamdoomspork@gmail.com
